version: '3.8'

services:
  db:
    image: mysql:8.0
#    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: dacn2023
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
    db-data: